In [1]:
import numpy as np 

In [2]:
data = np.arange(0,10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
data = np.arange(0, 20, 4)
data

array([ 0,  4,  8, 12, 16])

In [4]:
numbers = [5,7,6,8,9,3]
data = np.array(numbers)
data

array([5, 7, 6, 8, 9, 3])

In [5]:
# three separate lists, each representing temperature measurements of one day
day1 = [5,8,1,2]
day2 = [2,7,3,5]
day3 = [2,4,7,8]

# combine days into one list (a list of lists)
temperatures = [day1, day2, day3]

# convert a list of lists into a matrix
data = np.array(temperatures)
data

array([[5, 8, 1, 2],
       [2, 7, 3, 5],
       [2, 4, 7, 8]])

In [6]:
data = np.zeros(10)
data

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
data = np.ones(5)
data

array([1., 1., 1., 1., 1.])

In [8]:
# generate a numpy array / matrix of ones, 6 x 6 
data = np.ones((6, 6)).astype(int)
data

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])