In [5]:
import numpy as np 

In [9]:
%%html
<style>
table {margin-top: 16pt;}
td {font-family: Arial, Helvetica, sans-serif !important; font-weight: 600; white-space: normal !important;}
tr:nth-child(even) {background: #b0d9eb !important; color: black}
tr:nth-child(odd) {background: #8fb1bf !important; color: black}
</style>

In [10]:
# from 0 to 9
data = np.arange(0,10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# from 0 to 19, steps of 4 (0, 4, 8, 12, 16 etc.)
data = np.arange(0, 20, 4)
data

array([ 0,  4,  8, 12, 16])

In [12]:
# convert a list into a numpy array (vector)
numbers = [5,7,6,8,9,3]
data = np.array(numbers)
data

array([5, 7, 6, 8, 9, 3])

In [13]:
# three separate lists, each representing temperature measurements of one day
day1 = [5,8,1,2]
day2 = [2,7,3,5]
day3 = [2,4,7,8]

# combine days into one list (a list of lists)
temperatures = [day1, day2, day3]

# convert a list of lists into a matrix
data = np.array(temperatures)
data

array([[5, 8, 1, 2],
       [2, 7, 3, 5],
       [2, 4, 7, 8]])

In [14]:
# generate a numpy array / vector of zeroes
data = np.zeros(10)
data

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
# generate a numpy array / vector of ones
data = np.ones(5)
data 

array([1., 1., 1., 1., 1.])

In [16]:
# generate a numpy array / matrix of ones, 6 x 6 
data = np.ones((6, 6)).astype(int)
data

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [17]:
# without NumPy, you'd have to have a Python list, for-loop, and division calculations
data = np.linspace(0, 10, 5)
data

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [18]:
data = np.random.rand(5, 5)
data

array([[0.53654778, 0.5780235 , 0.34203803, 0.08601349, 0.60260791],
       [0.14240116, 0.32242457, 0.59499633, 0.99273741, 0.49277007],
       [0.77734518, 0.09624996, 0.27096447, 0.9507612 , 0.16486348],
       [0.86803734, 0.49842881, 0.33549567, 0.14251434, 0.32566525],
       [0.80995497, 0.44094549, 0.86316628, 0.68427968, 0.63769871]])

In [19]:
data = np.random.randn(5, 5)
data

array([[ 0.40339263, -0.14224416,  0.68416875,  2.65818286,  0.85254277],
       [-0.46546049, -0.74145006, -0.97375533, -0.61058085, -0.3948343 ],
       [-0.23127056, -0.12123267,  0.42873576,  1.65492066,  0.37943748],
       [ 1.95226136, -1.44387046, -1.83259526,  0.74015001, -1.31541862],
       [-0.71762125, -0.03941045, -0.69215869,  0.18311888,  0.30874571]])

In [20]:
data = np.random.randint(2000, 2100, 5)
data

array([2022, 2072, 2002, 2041, 2094])

In [21]:
data = np.arange(0, 100).reshape(5, 20)
data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [22]:
data = np.random.randint(0, 100, 25).reshape(5, 5)
data

array([[80,  5, 61, 55, 18],
       [76, 56,  9, 37, 64],
       [64, 17,  5, 80, 24],
       [63, 88, 41, 76, 65],
       [ 6, 10, 12, 88, 75]])

In [23]:
max_value = np.max(data)
max_value

88

In [24]:
data = np.random.randint(0, 100, 10)
data

array([40, 68, 63, 60, 60, 34, 87, 60, 26, 44])

In [25]:
data.max() 

87

In [26]:
data.argmax() 

6

In [27]:
data = np.random.randint(0, 100, 25).reshape(5, 5)
data

array([[96,  6, 16, 83, 53],
       [43, 96, 78, 43,  3],
       [ 3, 48, 47, 10, 34],
       [68, 51,  5, 29, 11],
       [83,  8, 20,  9, 28]])

In [28]:
data.argmax() 

0

In [29]:
data.shape 

(5, 5)

In [30]:
data = np.arange(0, 21, 2)
data

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [31]:
element = data[5]
element

10

In [32]:
slice = data[3:7]
slice

array([ 6,  8, 10, 12])

In [33]:
slice = data[:4]
slice

array([0, 2, 4, 6])

In [34]:
slice = data[5:]
slice

array([10, 12, 14, 16, 18, 20])

In [35]:
data = np.random.randint(0, 100, 25).reshape(5,5)
data

array([[36, 71, 76, 39,  6],
       [51, 71, 66, 98, 16],
       [69,  9, 63, 24, 26],
       [ 5, 60,  9, 25, 68],
       [16, 77, 54, 80, 15]])

In [36]:
data[3,4]

68

In [37]:
data[0]

array([36, 71, 76, 39,  6])

In [38]:
data[:2, 1:]

array([[71, 76, 39,  6],
       [71, 66, 98, 16]])

In [39]:
data = np.arange(0, 11)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
filtered = data[data > 5]
filtered

array([ 6,  7,  8,  9, 10])

In [41]:
filtered = data[data % 3 == 0]
filtered

array([0, 3, 6, 9])

In [42]:
data = np.arange(0,10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
data[0:5] = 100
data

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [44]:
slice = data[0:5]
slice[:] = 150
slice

array([150, 150, 150, 150, 150])

In [45]:
data

array([150, 150, 150, 150, 150,   5,   6,   7,   8,   9])

In [46]:
data = np.arange(0, 11)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
combined = data + data
combined

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [48]:
reduced = data - data
reduced

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [49]:
added = data + 200
added

array([200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210])

In [50]:
data = np.random.randint(100,500, 5)
data

array([121, 438, 162, 310, 465])

In [51]:
multiplied = data * 1.24
multiplied

array([150.04, 543.12, 200.88, 384.4 , 576.6 ])

In [52]:
data = np.ones(5).astype(int) * 7
data

array([7, 7, 7, 7, 7])

In [53]:
data = np.arange(0, 11)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
result = data / data
result

C:\Users\User\AppData\Local\Temp\ipykernel_24624\426602854.py:1: RuntimeWarning: invalid value encountered in divide
  result = data / data


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [55]:
result = 1 / data
result

C:\Users\User\AppData\Local\Temp\ipykernel_24624\4099404466.py:1: RuntimeWarning: divide by zero encountered in divide
  result = 1 / data


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [56]:
values = np.arange(0, 100).reshape(10, 10)
values

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [57]:
np.sum(values) 

4950

In [58]:
np.sum(values, axis=1) 

array([ 45, 145, 245, 345, 445, 545, 645, 745, 845, 945])

In [59]:
np.std(values) 

28.86607004772212