In [30]:
ones_list = [1] * 15
print("1. List of 15 ones:")
print(ones_list)


1. List of 15 ones:
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [31]:
sevens_list = [7] * 15
print("2. List of 15 sevens:")
print(sevens_list)


2. List of 15 sevens:
[7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]


In [32]:
range_list = list(range(100, 151))
print("3. Numbers from 100 to 150:")
print(range_list)


3. Numbers from 100 to 150:
[100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150]


In [33]:
even_list = [x for x in range(0, 101) if x % 2 == 0]
print("4. Even numbers between 0 and 100:")
print(even_list)


4. Even numbers between 0 and 100:
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [34]:
leap_years = [year for year in range(1950, 2021) if year % 4 == 0]
print("5. Leap years between 1950 and 2020:")
print(leap_years)


5. Leap years between 1950 and 2020:
[1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992, 1996, 2000, 2004, 2008, 2012, 2016, 2020]


In [35]:
import numpy as np

zeros_arr = np.zeros(15)
print("1. Array of 15 zeroes:")
print(zeros_arr)


1. Array of 15 zeroes:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [36]:
ones_arr = np.ones(15)
print("2. Array of 15 ones:")
print(ones_arr)


2. Array of 15 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [37]:
sevens_arr = np.full(15, 7)
print("3. Array of 15 sevens:")
print(sevens_arr)


3. Array of 15 sevens:
[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]


In [38]:
range_arr = np.arange(100, 151)
print("4. Numbers from 100 to 150:")
print(range_arr)


4. Numbers from 100 to 150:
[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150]


In [39]:
years_arr = np.arange(1900, 2022)
print("5. Years from 1900 to 2021:")
print(years_arr)


5. Years from 1900 to 2021:
[1900 1901 1902 1903 1904 1905 1906 1907 1908 1909 1910 1911 1912 1913
 1914 1915 1916 1917 1918 1919 1920 1921 1922 1923 1924 1925 1926 1927
 1928 1929 1930 1931 1932 1933 1934 1935 1936 1937 1938 1939 1940 1941
 1942 1943 1944 1945 1946 1947 1948 1949 1950 1951 1952 1953 1954 1955
 1956 1957 1958 1959 1960 1961 1962 1963 1964 1965 1966 1967 1968 1969
 1970 1971 1972 1973 1974 1975 1976 1977 1978 1979 1980 1981 1982 1983
 1984 1985 1986 1987 1988 1989 1990 1991 1992 1993 1994 1995 1996 1997
 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011
 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021]


In [40]:
even_arr = np.arange(0, 101, 2)
print("6. Even numbers between 0 and 100:")
print(even_arr)


6. Even numbers between 0 and 100:
[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [41]:
leap_arr = np.arange(1952, 2021, 4)
print("7. Leap years between 1950 and 2020:")
print(leap_arr)


7. Leap years between 1950 and 2020:
[1952 1956 1960 1964 1968 1972 1976 1980 1984 1988 1992 1996 2000 2004
 2008 2012 2016 2020]


In [42]:
matrix_7x7 = np.arange(1, 50).reshape(7, 7)
print("1. 7x7 matrix (1-49):")
print(matrix_7x7)


1. 7x7 matrix (1-49):
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42]
 [43 44 45 46 47 48 49]]


In [43]:
py_matrix = []
for i in range(7):
    row = list(range(1 + i*7, 8 + i*7))
    py_matrix.append(row)
print("Python list version:")
print(py_matrix)


Python list version:
[[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14], [15, 16, 17, 18, 19, 20, 21], [22, 23, 24, 25, 26, 27, 28], [29, 30, 31, 32, 33, 34, 35], [36, 37, 38, 39, 40, 41, 42], [43, 44, 45, 46, 47, 48, 49]]


In [44]:
random_matrix = np.random.uniform(0, 5, (8, 8))
print("2. 8x8 random matrix (0-5):")
print(random_matrix)


2. 8x8 random matrix (0-5):
[[3.14622609 2.29413409 2.68602377 1.95211475 2.69696618 4.24476979
  4.3016272  3.67270321]
 [2.15957413 0.85356527 2.14476162 1.90584155 0.14513546 1.54153659
  3.40841456 0.72527598]
 [1.60119542 1.73679557 2.57227734 3.6818686  1.67346294 2.43655845
  0.93710623 3.15277874]
 [1.18996034 0.6530877  1.30043224 0.99037694 3.71978738 4.77573907
  0.18719415 4.89808736]
 [4.63737192 2.19284537 2.45205037 0.51943828 4.41321567 1.34101923
  0.85248474 1.56428069]
 [1.52017284 0.2223161  0.23471155 3.53305927 4.13862431 1.33902847
  0.93207669 1.52242472]
 [2.38016184 3.34454676 4.34771126 3.22986409 3.78817925 4.37148512
  4.61218549 2.00819799]
 [2.54104654 1.99535623 4.56805637 0.47478675 3.92789977 1.49315726
  3.14126116 2.43616771]]


In [45]:
linspace_arr = np.linspace(0, 1, 10)
print("1. 10 values between 0 and 1:")
print(linspace_arr)


1. 10 values between 0 and 1:
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [46]:
linspace_matrix = np.linspace(0, 5, 100).reshape(10, 10)
print("2. 10x10 matrix between 0 and 5:")
print(linspace_matrix)


2. 10x10 matrix between 0 and 5:
[[0.         0.05050505 0.1010101  0.15151515 0.2020202  0.25252525
  0.3030303  0.35353535 0.4040404  0.45454545]
 [0.50505051 0.55555556 0.60606061 0.65656566 0.70707071 0.75757576
  0.80808081 0.85858586 0.90909091 0.95959596]
 [1.01010101 1.06060606 1.11111111 1.16161616 1.21212121 1.26262626
  1.31313131 1.36363636 1.41414141 1.46464646]
 [1.51515152 1.56565657 1.61616162 1.66666667 1.71717172 1.76767677
  1.81818182 1.86868687 1.91919192 1.96969697]
 [2.02020202 2.07070707 2.12121212 2.17171717 2.22222222 2.27272727
  2.32323232 2.37373737 2.42424242 2.47474747]
 [2.52525253 2.57575758 2.62626263 2.67676768 2.72727273 2.77777778
  2.82828283 2.87878788 2.92929293 2.97979798]
 [3.03030303 3.08080808 3.13131313 3.18181818 3.23232323 3.28282828
  3.33333333 3.38383838 3.43434343 3.48484848]
 [3.53535354 3.58585859 3.63636364 3.68686869 3.73737374 3.78787879
  3.83838384 3.88888889 3.93939394 3.98989899]
 [4.04040404 4.09090909 4.14141414 4.19191919 4

In [47]:
matrix_3x5 = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 7, 6],
    [5, 4, 3, 2, 1]
])
print("1. 3x5 matrix:")
print(matrix_3x5)


1. 3x5 matrix:
[[1 2 3 4 5]
 [6 7 8 7 6]
 [5 4 3 2 1]]


In [48]:
array_step = np.arange(0.1, 1.0, 0.2)
print("2. Stepped array:")
print(array_step)


2. Stepped array:
[0.1 0.3 0.5 0.7 0.9]


In [49]:
array_reshaped = np.arange(0.1, 1.8, 0.2).reshape(3, 3)
print("3. Reshaped array:")
print(array_reshaped)


3. Reshaped array:
[[0.1 0.3 0.5]
 [0.7 0.9 1.1]
 [1.3 1.5 1.7]]


In [50]:
dataset = np.arange(1, 37).reshape(6, 6)
print("Original dataset:")
print(dataset)


Original dataset:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [51]:
slice1 = dataset[1:3, 1:4]
print("1. Slice [[8,9,10],[14,15,16]]:")
print(slice1)


1. Slice [[8,9,10],[14,15,16]]:
[[ 8  9 10]
 [14 15 16]]


In [52]:
col_slice = dataset[:, 1]
print("2. Column slice [2,8,14,20,26,32]:")
print(col_slice)


2. Column slice [2,8,14,20,26,32]:
[ 2  8 14 20 26 32]


In [53]:
row_slice = dataset[-1, :]
print("3. Row slice [31,32,33,34,35,36]:")
print(row_slice)


3. Row slice [31,32,33,34,35,36]:
[31 32 33 34 35 36]


In [54]:
three_rows = dataset[1:4, :]
print("4. Three rows:")
print(three_rows)


4. Three rows:
[[ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [55]:
dataset = np.arange(1, 50).reshape(7, 7)
print("Original dataset:")
print(dataset)


Original dataset:
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42]
 [43 44 45 46 47 48 49]]


In [56]:
dataset_added = dataset + 50
print("1. Dataset + 50:")
print(dataset_added)


1. Dataset + 50:
[[51 52 53 54 55 56 57]
 [58 59 60 61 62 63 64]
 [65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78]
 [79 80 81 82 83 84 85]
 [86 87 88 89 90 91 92]
 [93 94 95 96 97 98 99]]


In [57]:
total_sum = np.sum(dataset)
print("2. Total sum:")
print(total_sum)

2. Total sum:
1225


In [58]:
odd_sum = np.sum(dataset[dataset % 2 != 0])
print("3. Sum of odd numbers:")
print(odd_sum)

3. Sum of odd numbers:
625


In [59]:
std_dev = np.std(dataset)
print("4. Standard deviation:")
print(std_dev)

4. Standard deviation:
14.142135623730951


In [60]:
row_sums = np.sum(dataset, axis=1)
print("5. Row sums:")
print(row_sums)


5. Row sums:
[ 28  77 126 175 224 273 322]


In [61]:
col_sums = np.sum(dataset, axis=0)
print("6. Column sums:")
print(col_sums)

6. Column sums:
[154 161 168 175 182 189 196]


In [62]:
print("Extra 1: Saving and loading matrix")
matrix_to_save = np.random.rand(15, 15)
np.savetxt('matrix.txt', matrix_to_save)
matrix_loaded = np.loadtxt('matrix.txt')
print("Matrix loaded from file:")
print(matrix_loaded)

Extra 1: Saving and loading matrix
Matrix loaded from file:
[[4.04380506e-01 5.38396280e-01 1.29539492e-03 6.24191426e-01
  1.61768530e-01 4.04326118e-01 4.69446503e-01 7.73942018e-01
  3.59871360e-01 9.04637269e-01 4.12430788e-01 7.90810142e-01
  4.91804277e-01 1.18678580e-01 1.74561870e-01]
 [2.55967950e-01 3.10104252e-01 2.70434858e-02 7.93493476e-01
  5.93351941e-01 8.39974090e-01 9.25355661e-01 1.25385303e-01
  9.45584929e-01 7.86690875e-02 6.87938067e-01 5.62045589e-01
  6.24125751e-01 4.11795309e-01 3.55004777e-01]
 [1.27335438e-01 8.07517382e-01 1.21415932e-01 6.23987372e-01
  9.65830430e-01 3.26277292e-01 2.96063756e-01 4.24652299e-01
  9.13725715e-01 1.81786379e-01 2.63814139e-01 1.95857742e-02
  7.56957165e-01 9.22394904e-01 9.06673886e-01]
 [2.14975434e-01 8.06406063e-01 2.70237014e-01 7.40965241e-01
  3.51015256e-02 7.27471964e-01 6.09777921e-01 8.86888051e-01
  8.05180798e-01 1.86204055e-01 3.76377707e-01 8.04764949e-03
  9.29634439e-01 5.19148189e-01 2.33948916e-01]
 [9.

In [63]:
print("Extra 2: Masked arrays")
matrix = np.random.randint(0, 51, (10, 10))
for _ in range(10):
    i, j = np.random.randint(0, 10, 2)
    matrix[i, j] = -100
masked_matrix = np.ma.masked_where(matrix == -100, matrix)
filled_matrix = masked_matrix.filled(0)
print("Matrix with faults replaced:")
print(filled_matrix)

Extra 2: Masked arrays
Matrix with faults replaced:
[[17 13  5 44 16 45 18 35 18 39]
 [ 9 19 20 36  3 43 34 29 25  0]
 [28 49 31 34  0 50 29 34 47 27]
 [16 36 25  5  7 42  0 45 19 21]
 [ 3 46  1 28 46  7  3 15 28 23]
 [19 28 49 24 25  6 14 41 44 19]
 [18 34 18 40  3 21  0  5 25  0]
 [ 5  0  0  0 10  0 34  0 32 17]
 [16 49  9 27  0  6  0 45 24 14]
 [27 48 25 20 20  8  0 10 22 39]]


In [64]:
print("Extra 3: argsort example")
years = np.random.randint(2010, 2021, 10)
prices = np.random.randint(2000, 60001, 10)
sorted_indices = np.argsort(years)
sorted_years = years[sorted_indices]
sorted_prices = prices[sorted_indices]
print("Sorted by years:")
print("Years:", sorted_years)
print("Prices:", sorted_prices)

Extra 3: argsort example
Sorted by years:
Years: [2010 2011 2013 2013 2014 2015 2019 2019 2020 2020]
Prices: [ 7127 32964 31115 39068 23644  4251 48541  9721 55431 21919]


In [65]:
print("Extra 4: Exploring NumPy features")
arr = np.array([1, 2, 3])
print("np.repeat example:", np.repeat(arr, 3))
matrix = np.array([[1, 2], [3, 4]])
print("np.ravel example:", np.ravel(matrix))
print("np.transpose example:", np.transpose(matrix))
print("np.round example:", np.round(np.random.rand(3,3), 2))

Extra 4: Exploring NumPy features
np.repeat example: [1 1 1 2 2 2 3 3 3]
np.ravel example: [1 2 3 4]
np.transpose example: [[1 3]
 [2 4]]
np.round example: [[0.32 0.66 0.53]
 [0.49 0.02 0.86]
 [0.21 0.98 0.9 ]]
